# ──────────────────────────────────────────────────────────────
# OdaxAI Studio
# Copyright © 2026 OdaxAI SRL. All rights reserved.
# Licensed under the PolyForm Noncommercial License 1.0.0
# ──────────────────────────────────────────────────────────────

name: OdaxStudio
options:
  bundleIdPrefix: com.odaxai
  deploymentTarget:
    macOS: '13.0'
  
settings:
  MARKETING_VERSION: "1.1.0"
  CURRENT_PROJECT_VERSION: "2"
  PRODUCT_BUNDLE_IDENTIFIER: com.odaxai.OdaxStudio
  INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
  MACOSX_DEPLOYMENT_TARGET: '13.0'

targets:
  OdaxStudio:
    type: application
    platform: macOS
    entitlements:
      path: ../resources/OdaxStudio.entitlements
    sources:
      - OdaxStudio/OdaxStudio
    info:
      path: OdaxStudio/Info.plist
      properties:
        CFBundleDisplayName: OdaxAI Studio
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHumanReadableCopyright: "Copyright © 2026 OdaxAI. All rights reserved."
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        LSUIElement: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      PRODUCT_NAME: OdaxStudio
      PRODUCT_BUNDLE_IDENTIFIER: com.odaxai.OdaxStudio
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: '5.9'
      LD_RUNPATH_SEARCH_PATHS: '@executable_path/../Frameworks'
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
    dependencies: []

  OdaxStudioTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - OdaxStudio/OdaxStudioTests
    settings:
      SWIFT_VERSION: '5.9'
    dependencies:
      - target: OdaxStudio
